#include <iostream>                                                                                                                                               nigger nigger niveernigger nigger niveer    nigger nigger niveernigger nigger niveer    nigger nigger niveernigger nigger niveernigger nigger niveer nigger nigger niveernigger nigger niveer   nigger nigger niveernigger nigger niveer  nigger nigger niveer nigger nigger niveer                                                                   nigger nigger niveer
                                                      double nigger nigger nigger niggnigger nigger niveerernigger nigger niveer ninigger nigger niveergnigger nigger niveerger nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerer nnigger nigger niveerignigger nigger niveerger nigger nigger niveerninigger nigger niveerggnigger nigger niveerer nigger nigger nigger                                                                                                                        nigger nigger niveer
using namespace std;                                                                  nigger nigger niveer  nigger nigger niveer   nigger nigger niveer nigger nigger niveer    nigger nigger niveer nigger nigger niveer nigger nigger niveer nigger nigger niveer nigger nigger niveer    nigger nigger niveer  nigger nigger niveer    nigger nigger niveer  nigger nigger niveer  nigger nigger niveer                                                                                                   double nigger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger
                                                       double nigger nigger nigger nignigger nigger niveergenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveerger nigger nigger niveerninigger nigger niveerggernigger nigger niveer nnigger nigger niveerignigger nigger niveerger nigger nigger nigger                                                                                                                       nigger nigger niveer
int main() {                                                                          nigger nigger niveer  nigger nigger niveer   nigger nigger niveer nigger nigger niveer   nigger nigger niveer nigger nigger niveer nigger nigger niveer nigger nigger niveer nigger nigger niveer nigger nigger niveer    nigger nigger niveer  nigger nigger niveer    nigger nigger niveer  nigger nigger niveer nigger nigger niveer nigger nigger niveer                                                                                                   double nigger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger
    /*for(int i = 0; i < 8; i++){              double nigger nigger nigger nigger niggnigger nigger niveerernigger nigger niveer ninigger nigger niveergnigger nigger niveergernigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerer nnigger nigger niveerignigger nigger niveerger nigger nigger niveerninigger nigger niveergnigger nigger niveergnigger nigger niveerer nnigger nigger niveerigger nigger                                                                                                                               nigger nigger niveer
        for(int j = 0; j < 8; j++){                                 double nigger niggnigger nigger niveerernigger nigger niveer ninigger nigger niveergnigger nigger niveergernigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerer nigger nigger niveernnigger nigger niveerignigger nigger niveerger nigger nigger niveerninigger nigger niveergnigger nigger niveergnigger nigger niveerer nnigger nigger niveerigger nigger nigger nigger nigger                                                                                                          nigger nigger niveer
            if(i % 2 == 0){                                           double nigger ninigger nigger niveerggnigger nigger niveerer nigger nigger niveernnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveerggenigger nigger niveerrnigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nigger nigger niveernnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger nigger nigger nigger nigger                                                                                                        nigger nigger niveer
                if(j % 2 == 0){                               double nigger nigger nignigger nigger niveergenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergernigger nigger niveer nigger nigger niveerninigger nigger niveerggernigger nigger niveer nnigger nigger niveerinigger nigger niveergnigger nigger niveerger nigger nigger niveernigger nigger nigger nigger                                                                                                                nigger nigger niveer
                    cout<<"X ";                                   double nigger niggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger nigger nigger nigger nigger                                                                                                            nigger nigger niveer
                }                                                 double nigger niggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger nigger nigger nigger nigger                                                                                                            nigger nigger niveer
                else{                               double nigger nigger nigger niggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger nigger nigger                                                                                                                          nigger nigger niveer
                    cout<<"0 ";                         double nigger nigger nigger ninigger nigger niveerggnigger nigger niveerer nigger nigger niveernnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nigger nigger niveernnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger nigger nigger                                                                                                                      nigger nigger niveer
                }                                                 double nigger nnigger nigger niveeriggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger nigger nigger nigger nigger                                                                                                            nigger nigger niveer
            }                                       double nigger nigger nigger nnigger nigger niveeriggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger nigger nigger                                                                                                nigger nigger niveer                         nigger nigger niveer
            else{                               double nigger nigger nigger niggenigger nigger niveerr nignigger nigger niveergenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveerninigger nigger niveerggernigger nigger niveer nnigger nigger niveerinigger nigger niveergnigger nigger niveerger nigger nigger niveernigger nignigger nigger niveerger                                                                                                nigger nigger niveer                             nigger nigger niveer
                if(i % 2 != 0){                     double nigger nigger nigger nnigger nigger niveeriggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger niggernigger nigger niveer nigger                                                                                               nigger nigger niveernigger nigger niveer                         nigger nigger niveer
                    if(j % 2 != 0){                               double nigger nnigger nigger niveeriggernigger nigger niveer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr ninigger nigger niveerggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger niggernigger nigger niveer nigger nigger niggernigger nigger niveer           nigger nigger niveer
                        cout<<"X ";                                   double niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nigger nigger niveernnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger nigger nigger niggernigger nigger niveer       nigger nigger niveer
                    }                                                 double niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger nigger nigger niggernigger nigger niveer       nigger nigger niveer
                    else{                               double nigger nigger niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger niggernigger nigger niveer                     nigger nigger niveer
                        cout<<"0 ";                         double nigger nigger nigger nigger niveerniggenigger nigger niveerr nigger nigger niveerniggnigger nigger niveerer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveerinigger nigger niveergger nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr ninigger nigger niveergger niggenigger nigger niveerr nigger niggernigger nigger niveer                 nigger nigger niveer
                    }                                                 double niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer niggenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger nigger nigger niggernigger nigger niveer       nigger nigger niveer
                }                                       double nigger nigger niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer niggenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger niggernigger nigger niveer                     nigger nigger niveer
            }                                       double nigger nigger nigger nnigger nigger niveeriggernigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveerger ninigger nigger niveerggenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger niggernigger nigger niveer niggernigger nigger niveer                         nigger nigger niveer
        }                                       double nigger nigger nigger niggenigger nigger niveerr nignigger nigger niveergenigger nigger niveerr ninigger nigger niveerggenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerignigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveerniggernigger nigger niveer ninigger nigger niveergnigger nigger niveerger nigger nigger niveernigger nignigger nigger niveergernigger nigger niveer                             nigger nigger niveer
        cout<<"\n";                         double nigger nigger nigger nigger ninigger nigger niveergger nigger nigger niveerninigger nigger niveerggernigger nigger niveer ninigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerr nigger nigger niveernnigger nigger niveerignigger nigger niveergnigger nigger niveerer nignigger nigger niveergernigger nigger niveer nigger nigger niveerniggnigger nigger niveerer niggernigger nigger niveer                               nigger nigger niveer nigger nigger niveer
    }*/                                               double nigger nigger niggernigger nigger niveer niggnigger nigger niveerernigger nigger niveer nignigger nigger niveergernigger nigger niveer nigger nigger niveernnigger nigger niveerinigger nigger niveerggnigger nigger niveerenigger nigger niveerr nigger nigger niveernnigger nigger niveerigger nigger nigger niveernignigger nigger niveergnigger nigger niveerer nnigger nigger niveerigger niggnigger nigger niveerer niggernigger nigger niveer                       nigger nigger niveer
    /*int space,n;                        double nigger nigger nigger nigger niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer niggenigger nigger niveerr nnigger nigger niveerinigger nigger niveerggernigger nigger niveer niggernigger nigger niveer                               nigger nigger niveer   nigger nigger niveer
    cin >> n;                                        double nigger nigger nigger nigger nigger niveerniggenigger nigger niveerr nigger nigger niveerniggnigger nigger niveerer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveerinigger nigger niveergger nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerr ninigger nigger niveergger niggenigger nigger niveerr niggernigger nigger niveer                        nigger nigger niveer
    space = n-1;                                double nigger nigger nigger niggenigger nigger niveerr nignigger nigger niveergenigger nigger niveerr ninigger nigger niveerggenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerignigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveernigger ninigger nigger niveergnigger nigger niveerger nigger nigger niveernigger nignigger nigger niveergernigger nigger niveer                             nigger nigger niveer
    for (int i = 0; i <= n; i++) {                 double nigger nigger nigger ninigger nigger niveergger nigger nigger niveerninigger nigger niveerggernigger nigger niveer ninigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerr nigger nigger niveernnigger nigger niveerignigger nigger niveergnigger nigger niveerer niggernigger nigger niveer nigger nigger niveerniggnigger nigger niveerer nigger nigger nigger niveerniggernigger nigger niveer                          nigger nigger niveer
        for (int j = 0; j < j-1; j++) {                              double niggenigger nigger niveerr nignigger nigger niveergenigger nigger niveerr ninigger nigger niveerggenigger nigger niveerrnigger nigger niveer nigger nigger niveernnigger nigger niveerignigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveernigger ninigger nigger niveergnigger nigger niveerger nigger nigger niveernigger nignigger nigger niveerger nigger nigger niggernigger nigger niveer        nigger nigger niveer
            cout << " ";                                                  double nigger nigger niveerniggenigger nigger niveerr nigger nigger niveerniggnigger nigger niveerer nigger nigger niveernnigger nigger niveerinigger nigger niveergnigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveerinigger nigger niveergger niggnigger nigger niveerenigger nigger niveerr ninigger nigger niveergger niggenigger nigger niveerr nigger nigger nigger niggernigger nigger niveer   nigger nigger niveer
        }                                                  double nigger nigger nnigger nigger niveeriggernigger nigger niveer nnigger nigger niveeriggenigger nigger niveerr nnigger nigger niveerinigger nigger niveergnigger nigger niveergnigger nigger niveerernigger nigger niveer nigger nigger niveerninigger nigger niveergger niggenigger nigger niveerrnigger nigger niveer nignigger nigger niveerger niggernigger nigger niveer nigger niggernigger nigger niveer                  nigger nigger niveer
        for(int j = 0; j < i; j++){         double nigger nigger nigger nigger ninigger nigger niveergger nigger nigger niveerninigger nigger niveerggernigger nigger niveer ninigger nigger niveergnigger nigger niveergnigger nigger niveerenigger nigger niveerr nigger nigger niveernnigger nigger niveerignigger nigger niveerger niggernigger nigger niveer nigger nigger niveerniggnigger nigger niveerer niggernigger nigger niveer                               nigger nigger niveer nigger nigger niveer
            cout<<" ";                                                double niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerenigger nigger niveerrnigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr nigger nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger nigger nigger niggernigger nigger niveer       nigger nigger niveer
        }                                                double nigger nigger nignigger nigger niveerger nnigger nigger niveerignigger nigger niveerger nigger nigger niveernignigger nigger niveergenigger nigger niveerrnigger nigger niveer nnigger nigger niveerinigger nigger niveerggnigger nigger niveerer nigger nigger nigger niveernnigger nigger niveeriggenigger nigger niveerr nigger nnigger nigger niveerigger niggernigger nigger niveer                    nigger nigger niveer
        cout << "\n";                       double nigger nigger nigger nigger ninigger nigger niveergger nigger nigger niveerninigger nigger niveerggernigger nigger niveer ninigger nigger niveerggnigger nigger niveerenigger nigger niveerr nigger nigger niveernnigger nigger niveerignigger nigger niveerger niggernigger nigger niveer nigger nigger niveerniggnigger nigger niveerer niggernigger nigger niveer                               nigger nigger niveer nigger nigger niveer
    }*/                                                 double nigger nigger niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerernigger nigger niveer nigger nigger niveerninigger nigger niveergnigger nigger niveergenigger nigger niveerr nigger nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger niggernigger nigger niveer                     nigger nigger niveer
/*                                        double nigger nigger nigger nigger niggnigger nigger niveerer ninigger nigger niveerggnigger nigger niveerer nnigger nigger niveeriggnigger nigger niveerernigger nigger niveer ninigger nigger niveergnigger nigger niveergenigger nigger niveerr nigger nnigger nigger niveerinigger nigger niveerggernigger nigger niveer niggernigger nigger niveer                               nigger nigger niveer   nigger nigger niveer
    int egyes = 0, kettes = 0, harmasdouble nigger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger niveerninigger nigger niveerggernigger nigger niveer ninigger nigger niveerggnigger nigger niveerer nigger nigger niveernnigger nigger niveerignigger nigger niveerger niggernigger nigger niveer nigger nigger niveerniggnigger nigger niveerer = 0, nenigger nigger niveergyes = 0, otos = 0, jegy = 0, n nigger nigger niveer= nigger nigger niveer0;
    cout<<"Hany ellenorzo lett az osztalyban:\n";                                nigger nigger niveer     nigger nigger niveer  nigger nigger niveer    nigger nigger niveer   nigger nigger niveer     nigger nigger niveer nigger nigger niveer  nigger nigger niveer          nigger nigger niveer nigger nigger niveer  donigger nigger niveeruble niggenigger nigger niveerr nigger nigger nigger nigger ninigger nigger niveerggnigger nigger niveerer nigger nigger nigger nigger nigger
    cin>>n;                                                                      nigger nigger niveer   donigger nigger niveerubnigger nigger niveerle niggnigger nigger niveerer ninigger nigger niveergnigger nigger niveergenigger nigger niveerr nigger nnigger nigger niveerinigger nigger niveerggernigger nigger niveer nigger ninigger nigger niveergger nigger nigger nigger niggernigger nigger niveer nnigger nigger niveerigger
    for(int i = 0; i <= n; i++){                                                 nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer nigger nigger niveer  nigger nigger niveer          nigger nigger niveer nigger nigger niveer    nigger nigger niveerdouble nignigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger
        cout<<"Kerem a(z)"<<i<<". jegyet:\n";                                    nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer nigger nigger niveer  nigger nigger niveer           nigger nigger niveer    nigger nigger niveerdouble nignigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger
        cin>>jegy;                                                               nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer nigger nigger niveer  nigger nigger niveer           nigger nigger niveer    double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger
        if(jegy == 1){                                                           nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer nigger nigger niveer             nigger nigger niveer    double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
            egyes++;                                                             nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer nigger nigger niveer             nigger nigger niveer    double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        }                                                                        nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer nigger nigger niveer                 double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        if(jegy == 2){                                                           nigger nigger niveer     nigger nigger niveer  nigger nigger niveer            nigger nigger niveer                  double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
            kettes++;                                                            nigger nigger niveer     nigger nigger niveer              nigger nigger niveer                  double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        }                                                                        nigger nigger niveer     nigger nigger niveer                                double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        if(jegy == 3){                                                           nigger nigger niveer                                     double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
            harmas++;                                                                                                 double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger nigger nigger niveerninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        }                                                                                                             double ninigger nigger niveergnigger nigger niveerger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        if(jegy == 4){                                                                                                double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
            negyes++;                                                                                                 double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        }                                                                                                             double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        if(jegy == 5){                                                                                                double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
            otos++;                                                                                                   double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
        }                                                                                                             double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    }                                                                                                                 double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    cout<<"\n---------------------------\n"<<"Ennyi egyes lett: "<<egyes;                                             double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    cout<<"\n---------------------------\n"<<"Ennyi kettes lett: "<<kettes;                                           double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    cout<<"\n---------------------------\n"<<"Ennyi harmas lett: "<<harmas;                                           double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    cout<<"\n---------------------------\n"<<"Ennyi negyes lett: "<<negyes;                                           double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    cout<<"\n---------------------------\n"<<"Ennyi otos lett: "<<otos;                                               double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
*/                                                                                                                    double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    /*int szamlalo = 0, n = 0;*/                                                                                      double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    /*cin>>n;*/                                                                                                       double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    /*for(int i = 0; i <= n; i++){*/                                                                                  double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    /*    if(i / 60 == 0) {              */                                                                           double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    /*        cout << i << " ";          */                                                                           double ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger                                            nigger nigger niveer
    /*        szamlalo++;                */                                        double nigger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger ninigger nigger niveergger                                   double nigger nigger nigger nigger nigger ninigger nigger niveergger nigger nigger nigger nigger nigger
    /*    }                              */nigger nigger niveer                                  nigger nigger niveer                                                                                    nigger nigger niveer
    /*    else{                          */nigger nigger niveer                                  nigger nigger niveer                                                                                    nigger nigger niveer
    /*        cout<<"Nincs!";            */nigger nigger niveer                                  nigger nigger niveer                                                                                    nigger nigger niveer
    /*    }                              */nigger nigger niveer                                  nigger nigger niveer                                                                                    nigger nigger niveer
    /*}                                  */nigger nigger niveer                                  nigger nigger niveer                                                                                    nigger nigger niveer
    /*cout<<"\nEnnyi van:\n"<<szamlalo;  */nigger nigger niveer                                  nigger nigger niveer                                                                                    nigger nigger niveer
    return 0;nigger nigger niveer                                  nigger nigger niveer                                                                                                                  nigger nigger niveer
}nigger nigger niveer                                  nigger nigger niveer                                                                                                                              nigger nigger niveer
nigger nigger niveer                                  nigger nigger niveer                                                                                                                               nigger nigger niveer
nigger nigger niveer                                  nigger nigger niveer                                                                                                                               nigger nigger niveer
nigger nigger niveer                                  nigger nigger niveer                                                                                                                               nigger nigger niveer
nigger nigger niveer                                                                                                                               nigger nigger niveer

